### ISSUE TITLE
Building with X11 is broken

### ISSUE THREAD

**Issue by finalpatch** [BeRo1985/pasvulkan#1]
There are 2 issues under X11
* Some Win32 function prototypes are not guarded by {$ifdef Windows}
* A couple symbols in PasVulkan.pas should be 'Xlib' instead of 'X11'

See attachments for my patches.

[p1.diff.txt](https://github.com/BeRo1985/pasvulkan/files/503341/p1.diff.txt)
[p2.diff.txt](https://github.com/BeRo1985/pasvulkan/files/503340/p2.diff.txt)

After these patches the library compiles for me under Ubuntu (still doesn't really work because I tried in VMware which lacks proper driver).

**Comment by BeRo1985** [comment]
Fixed :-)
