### ISSUE TITLE
Support for VK_KHR_mir_surface should be removed

### ISSUE THREAD

**Issue by jekstrand** [BeRo1985/pasvulkan#11]
See also: https://github.com/KhronosGroup/Vulkan-Docs/issues/814

**Comment by BeRo1985** [comment]
At PasVulkan, the WSI support is controlled by compile-time-defines, so as a first step I have now removed the MIR-define from the default-defines for the Linux target, and as soon as it is completely removed from the specification, I will remove it completely. 

At least thank you very much for the hint.
