### ISSUE TITLE
Failing to load "libvulkan.so"

### ISSUE THREAD

**Issue by WayneSherman** [BeRo1985/pasvulkan#13]
On Kubuntu 18.04 with updated video stack pasvulkan fails to load "libvulkan.so" which doesn't exist.  If you are only targeting Vulkan 1 at the moment, perhaps it would be better to link to "libvulkan.so.1" specifically for now.

Changing line 92 in Vulkan.pas fixes it:
`const VK_DEFAULT_LIB_NAME={$ifdef Windows}'vulkan-1.dll'{$else}{$ifdef Unix}'libvulkan.so.1'{$else}'libvulkan'{$endif}{$endif};
`

Reference [Vulkan Loader Docs](https://github.com/KhronosGroup/Vulkan-Loader/blob/master/loader/LoaderAndLayerInterface.md#interfacing-with-vulkan-functions):

> For Linux and MacOS, shared libraries are versioned based on a suffix. Thus, the ABI number is not encoded in the base of the library filename as on Windows. On Linux an application wanting to link to the latest Vulkan ABI version would just link to the name vulkan (libvulkan.so). A specific Vulkan ABI version can also be linked to by applications (e.g. libvulkan.so.1). On MacOS, the libraries are libvulkan.dylib abd libvulkan.1.dylib.

**Comment by BeRo1985** [comment]
Fixerd but this is actually a Ubuntu and Debian issue, so please you should report it also there, because another Distros like ArchLinux and so on have also a libvulkan.so symlink (as the spec it also say "On Linux an application wanting to link to the latest Vulkan ABI version would just link to the name vulkan (libvulkan.so)"), and Android have also only libvulkan.so and not libvulkan.so.1.

**Comment by BeRo1985** [comment]
Okay, I found why: at Ubuntu and Debian, the libvulkan.so symlink is inside the libvulkan-dev package ( https://packages.ubuntu.com/bionic/amd64/libvulkan-dev/filelist ) instead inside the normal non-dev vulkan packages, but what it was supposed to be like actually according to the specification.

**Comment by WayneSherman** [comment]
I found this which defines how Debian names libraries:
https://www.debian.org/doc/debian-policy/ch-sharedlibs.html

> The development package should contain a symlink for the associated shared library without a version number. For example, the libgdbm-dev package should include a symlink from /usr/lib/libgdbm.so to libgdbm.so.3.0.0. This symlink is needed by the linker (ld) when compiling packages, as it will only look for libgdbm.so when compiling dynamically.
