### ISSUE TITLE
Error compiling Vulkan.pas with FPC trunk 3.3.1

### ISSUE THREAD

**Issue by soerensen3** [BeRo1985/pasvulkan#16]
When compiling Vulkan.pas with the latest FPC trunk it fails because of the VK_ACCESS_RESERVED_31_BIT_KHR having a too large value:
Vulkan.pas(2923,47) Error: Enumeration symbols can only have values in the range of -2^31 to 2^31-1
    
     TVkAccessFlagBits=
      (
       VK_ACCESS_RESERVED_31_BIT_KHR=$80000000, //<--- ISSUE HERE
       VK_ACCESS_INDIRECT_COMMAND_READ_BIT=$00000001,                            //< Controls coherency of indirect command reads
       VK_ACCESS_INDEX_READ_BIT=$00000002,                                       //< Controls coherency of index reads
       VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT=$00000004,                            //< Controls coherency of vertex attribute reads
       VK_ACCESS_UNIFORM_READ_BIT=$00000008,                                     //< Controls coherency of uniform buffer reads
       VK_ACCESS_INPUT_ATTACHMENT_READ_BIT=$00000010,       `

**Comment by BeRo1985** [comment]
You should  report it into the FPC own bugtracker at https://bugs.freepascal.org/  since it compiles with older FPC versions and with Delphi
