### ISSUE TITLE
idea for better png loading time performance 

### ISSUE THREAD

**Issue by codz01** [BeRo1985/pasvulkan#17]
Hi Bero
based on discussion in (https://forum.lazarus.freepascal.org/index.php/topic,49940.msg363534/topicseen.html)
 I've tried moving some local vars (used by nested proc/fun ) and make them global in (PasVulkan.Image.PNG.pas) . 
the loading speed is increased about 25%    \o/

**Comment by BeRo1985** [comment]
Unfortunately this suggestion prevents the use in multithreaded situations, where the PNG loader code is called in many CPU threads parallel at the same time, so it is not a practical solution.
