### ISSUE TITLE
GetPhysicalDeviceFeatures2KHR failing in TpvVulkanPhysicalDevice.Create

### ISSUE THREAD

**Issue by johnhutch111** [BeRo1985/pasvulkan#25]
if not assigned(vkGetPhysicalDeviceProperties2KHR) then begin
  @vkGetPhysicalDeviceProperties2KHR:=vkVoidFunctionToPointer(vkGetProcAddress(LibVulkan,'vkGetPhysicalDeviceProperties2KHR'));
   @vk.fCommands.GetPhysicalDeviceProperties2KHR:=addr(vkGetPhysicalDeviceProperties2KHR);
  end;

vkGetPhysicalDeviceProperties2KHR returns nil in LoadVulkanGlobalCommands

 if (fInstance.APIVersion and VK_API_VERSION_WITHOUT_PATCH_MASK)=VK_API_VERSION_1_0 then begin
  fInstance.Commands.GetPhysicalDeviceFeatures2KHR(Handle,@fFeatures2KHR);
 end else begin
  fInstance.Commands.GetPhysicalDeviceFeatures2(Handle,@fFeatures2KHR);
 end;

Fails when fInstance.APIVersion = VK_API_VERSION_1_0 
OK when GetPhysicalDeviceFeatures2 is called

VK_KHR_get_physical_device_properties2 extension NOT available on my NVIDIA RTX 3080 or Intel UHD hardware. 

Vulkan API version 1.2.162.
Any Suggestions??

**Comment by johnhutch111** [comment]
It seems ALL the procedures with  ...2KHR are returning NIL during the LoadVulcanGlobalCommands

**Comment by BeRo1985** [comment]
Hm, I'm currently working with a NVIDIA Geforce RTX3070 Mobile on PasVulkan. Which NVIDIA driver version you have? I've 512.59. But I'll double check by enforcing a Vulkan 1.2 context later.

**Comment by BeRo1985** [comment]
Hm, are you working with a Vulkan 1.0, 1.1, 1.2 or 1.3 context? Since vkGetPhysicalDeviceProperties2KHR does exist only at Vulkan 1.0, since it was promoted to a Core API at Vulkan 1.1, see   https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceProperties2.html .

**Comment by BeRo1985** [comment]
![image](https://user-images.githubusercontent.com/428863/176975799-64969a08-dee3-4a31-9df8-c7d4c52a9a4c.png)

At my NVIDIA RTX3070 Mobile with driver version 512.59 vkGetPhysicalDeviceProperties2KHR  does exist, even at >= Vulkan 1.1 contexts.

**Comment by BeRo1985** [comment]
As well at my Intel Iris Xe Graphics iGPU (Intel Core i7 11370H)

**Comment by BeRo1985** [comment]
![image](https://user-images.githubusercontent.com/428863/176976010-7a67ac4b-00ed-446d-b51f-605ed408df1a.png)

So ignore it from LoadVulkanGlobalCommands  and instead use it from   LoadVulkanInstanceCommands . Vulkan is differencely layered here in this context, where not all API functions are already directly usable as global commands, but rather first later as instance commands or even later as device commands.

**Comment by BeRo1985** [comment]
This also means fInstance.Commands is from LoadVulkanInstanceCommands and not from LoadVulkanGlobalCommands. So I see no issue here?

**Comment by johnhutch111** [comment]
I am using the same NVIDIA driver 512.59.
In my original post, the code ..

_if (fInstance.APIVersion and VK_API_VERSION_WITHOUT_PATCH_MASK)=VK_API_VERSION_1_0 then begin
fInstance.Commands.GetPhysicalDeviceFeatures2KHR(Handle,@fFeatures2KHR);
end else begin
fInstance.Commands.GetPhysicalDeviceFeatures2(Handle,@fFeatures2KHR);
end;_

comes from pasvulkan.framework and does use fInstance.Commands as suggested.  This is where the first fail is.

Shouldn't the code be something like..

if (fInstance.APIVersion and VK_API_VERSION_WITHOUT_PATCH_MASK)=VK_API_VERSION_1_0 **_AND Assigned(fInstance.Commands.GetPhysicalDeviceFeatures2KHR)_** then begin
fInstance.Commands.GetPhysicalDeviceFeatures2KHR(Handle,@fFeatures2KHR);
end else begin
fInstance.Commands.GetPhysicalDeviceFeatures2(Handle,@fFeatures2KHR);
end;

**Comment by johnhutch111** [comment]
I can see why my last post won't work.  

You use a lot of fInstance.APIVersion  to test the current version for call availability.  As this is user selected shouldn't there be another APIVersion which reflects the ACTUAL version of the API and not the user selected version.  Or there needs another mechanism to handle the depricated calls.

Perhaps assigning the Procedure entry point for the new version to the old version in this case may work?? 

 if not assigned(vkGetPhysicalDeviceProperties2KHR) then begin
   @vkGetPhysicalDeviceProperties2KHR:=vkVoidFunctionToPointer(vkGetProcAddress(LibVulkan,'vkGetPhysicalDeviceProperties2KHR'));
   _**If not assigned(vkGetPhysicalDeviceProperties2KHR) then
      @vkGetPhysicalDeviceProperties2KHR:= @vkGetPhysicalDeviceProperties2;**_
   @vk.fCommands.GetPhysicalDeviceProperties2KHR:=addr(vkGetPhysicalDeviceProperties2KHR);
  end;

**Comment by johnhutch111** [comment]
In my system (Delphi XE8) fInstance.Commands.GetPhysicalDeviceProperties2KHR is NIL.

**Comment by johnhutch111** [comment]
That fixed it.  Thanks
