### ISSUE TITLE
Compile Problems on Delphi XE8

### ISSUE THREAD

**Issue by johnhutch111** [BeRo1985/pasvulkan#26]
Compile Problems on Delphi XE8...
Latest version of PasVulkan.Math is failing to compile.  TpvAABB Class Function Intersect causes errors E2254,E2169,E2033
Latest version of PasVulkan.Framework is failing to compile.  TpvVulkanBuffer Class Procedure ProcessCopyBatch causes errors E2169, E2058

**Comment by johnhutch111** [comment]
Also fails on Delphi 11

**Comment by BeRo1985** [comment]
Can you please try https://github.com/BeRo1985/pasvulkan/commit/239f4bb690d44f3b3386443e93ff74f6eaa44ca1 ?

**Comment by BeRo1985** [comment]
I'm install currently Delphi 11 on my new computer, so that I can test myself then.

**Comment by johnhutch111** [comment]
Yes the fix works OK.  
Couple of other problems in PasVulkan.Math
class function TpvAABB.RayIntersection has "inline" in implementation which isn't in declaration.  Fails on this.
Implementation of constructor TpvVulkanBuffer.Create(... const aBufferFlags:TpvVulkanBufferFlags**=[]**) has value assigned to aBufferFlags which causes the compiler to fail.  Need to remove the value.

**Comment by BeRo1985** [comment]
But now, it should work at leasr with Delphi 11 :-) See https://twitter.com/coder/status/1568426260581306369 and https://www.facebook.com/benjamin.rosseaux/posts/pfbid02xycJrE9QpNA878vWNy7jtBvkGT582J6gVTjq4sb3Y9hgZhVHPaQzqy1SmeFxqSDml
