### ISSUE TITLE
PasVulkan Framework TpvTexture fSampler issue

### ISSUE THREAD

**Issue by johnhutch111** [BeRo1985/pasvulkan#36]
I am using a TpvTexture.  I want to use an external fsampler.  However, If I call the TpvTexture.Finish routine the fsampler (whether internal or External) is set to NIL.  This is the same for the fImage and fImageView. 

If I want to assign an external sampler then I MUST assign after the Finish call.  Is this correct?   

It also seems the internal fSampler (if used) is NOT deleted correctly.  I am not sure if this is true for the fImage and the fImageView.  

Any comments?
John

**Comment by BeRo1985** [comment]
Should be fixed now, please test :-)

**Comment by johnhutch111** [comment]
Thanks, looks good.
