### ISSUE TITLE
license

### ISSUE THREAD

**Issue by nikolajbotalov** [BeRo1985/pasvulkan#37]
Hello there.
I am interested in your BRTECH1 engine.
How do I get license? How much does it cost?
Please, give more info on BRTECH1.
Sorry for off topic

**Comment by BeRo1985** [comment]
Thank you for your inquiry! Could you please provide more details about your use case? I'm currently busy with a PasVulkan-based project (for food / for living), but I will be able to write a detailed response by Wednesday.
