### ISSUE TITLE
Feature request: parallel textures load for gltfviwer and ktx2

### ISSUE THREAD

**Issue by tigrazone** [BeRo1985/pasvulkan#39]
Is it possible to implement?
One more question. Is ktx2 loading is supported?

**Comment by BeRo1985** [comment]
Parallel loading is already implemented, but it’s lock-stepped to ensure a safe loading process. This approach also makes it easier for PasVulkan to deduplicate textures, helping to save RAM. KTX2 is supported, including BASISU texture compression, as long as ktx.dll and ktx_read.dll (for Windows) or libktx.so and libktx_read.so (for Linux/*nix) are present. These files are also available in the PasVulkan Git repository.

**Comment by tigrazone** [comment]
what you mean  "lock-stepped"?
not parallel? or what?
other information is awesome and promising

**Comment by BeRo1985** [comment]
Locked-stepped means that these are currently still processed almost sequentially within GLTFs (but this will change later), but GLTFs themselves can be loaded in parallel. Outside GLTFs, textures can be loaded or pre-decoded in parallel and afterwards uploaded sequentially, also to avoid sync problems. See `PasVulkan.Resources.pas` how parallel resource loading are working here.
