### ISSUE TITLE
Maximized windows go off screen in GUI example

### ISSUE THREAD

**Issue by troneill** [BeRo1985/pasvulkan#4]
It appears maximized windows in the GUI example go off screen because the initial menu bar is not recognized as a parent during window state change?

Built with Lazarus 1.6.4/FPC 3.0.2

![examples](https://user-images.githubusercontent.com/32448130/33218897-ff391138-d104-11e7-96e0-70a6f95f4ace.png)

**Comment by BeRo1985** [comment]
Fixed at https://github.com/BeRo1985/pasvulkan/commit/bdd02085cdc6ef331260bc27310b12154be37991 :)

**Comment by BeRo1985** [comment]
And as a tip: if you compile it with the global define NoVSync with -dNoVSync as FPC compiler parameter, then the GUI will react much smoother to mouse movements and so on, since the input processing is no more limited to the display framerate then.
