### ISSUE TITLE
projectmanager fails to find fpc on linux

### ISSUE THREAD

**Issue by WayneSherman** [BeRo1985/pasvulkan#9]
src/tools/projectmanager/UnitProject.pas

function FindBinaryInExecutableEnviromentPath searches the current PATH using a ";" (semicolon) to separate PATH entries:

[UnitProject.pas, Line 50](https://github.com/BeRo1985/pasvulkan/blob/master/src/tools/projectmanager/UnitProject.pas#L50):  `PathStringList.Delimiter:=';';`

Linux uses a ":" (colon) to delimit path entries, so the fpc executable is never found.

Linux path example:
```
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by BeRo1985** [comment]
Fixed
